# Generated by Django 3.2.16 on 2022-12-13 17:08

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='images',
            field=models.ImageField(blank=True, upload_to=store.models.category_image_file_path),
        ),
    ]
